### Create a new category
POST http://localhost:3001/transactions
content-type: application/json

{
    "userId": "2",
    "description": "income",
    "amount": 99,
    "transactionDate": "2024-11-22T06:36:57",
    "categoryId": "2"
}




### Find all transactions
GET  http://localhost:3001/transactions


